// Generated by https://quicktype.io

export interface DeliveryModel {
    id: number;
    user_id: number;
    calification: string;
    description: string;
    placa: string;
    vehicle: Vehicle;
    deleted_at: null;
    created_at: string;
    updated_at: string;
}

export enum Vehicle {
    Automovil = "automovil",
    Moto = "moto",
}
